<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

for i in datos
# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [3]:
import numpy as np

lista = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
array_unidimensional = np.array(lista)

print(type(array_unidimensional))


<class 'numpy.ndarray'>


#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [4]:
array_2D = np.reshape(array_unidimensional,(2 ,5))

print(array_2D)

[[0 1 2 3 4]
 [5 6 7 8 9]]


#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [5]:
ejemplo = [0, 2, 0, 3, 0, 4, 0]
array_ejemplo = np.array(ejemplo)

resultado_where = np.where(array_ejemplo > 0)
print(resultado_where)
        


(array([1, 3, 5]),)


#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [6]:
array_randint_tri = np.random.randint(0, 2, (3,3))
print(array_randint_tri)

[[0 0 1]
 [0 0 0]
 [1 1 1]]


#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [7]:
array_10 = np.random.randint(0, 100000, 10)
print(array_10)
print(type(array_10))

[92936 52630 38118  1417 60464 58395 73056 41255 38685 88073]
<class 'numpy.ndarray'>


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [8]:
lista_array = [1, 2, 3, 4, 5, 6]
array_1D = np.array(lista_array)
print(array_1D)

reshaped_array_1D = np.flip(array_1D)
print(reshaped_array_1D)

[1 2 3 4 5 6]
[6 5 4 3 2 1]



#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [9]:
#Comentado para evitar que al ejecutar modifique el array creado.
#array_tridi = np.random.randint(1, 24, (2, 3, 4))
#Lo copio a mano tras crearlo random

array_tridi = np.array([[[22, 13, 6, 11],
                        [11, 10, 12, 23],
                        [6, 4, 20, 13]],

                        [[15, 16, 19, 19],
                        [22, 15, 12, 22],
                        [1, 10, 19, 1]]])

print(array_tridi)

print("---------------------------------")
      
resultado_where = np.where(array_tridi == 15)
array_primer_15 = resultado_where[0]
print(array_primer_15)

print("---------------------------------")
primer_array = array_tridi[0]
primera_fila = primer_array[0]
print(primera_fila)

print("---------------------------------")

ultimo_array = array_tridi[-1]
ultima_fila = ultimo_array[-1]
print(ultima_fila)




[[[22 13  6 11]
  [11 10 12 23]
  [ 6  4 20 13]]

 [[15 16 19 19]
  [22 15 12 22]
  [ 1 10 19  1]]]
---------------------------------
[1 1]
---------------------------------
[22 13  6 11]
---------------------------------
[ 1 10 19  1]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [10]:
#Genero con random y luego lo copio y defino a mano.
#array_triple = np.random.randint(1, 30, (3, 2, 5))

array_triple = np.array([[[14, 21, 2, 20, 28],
                        [28, 15, 14, 25, 6]],

                        [[10, 25, 26, 27, 8],
                        [14, 7, 22, 28, 2]],

                        [[3, 10, 10, 10, 13],
                        [3, 19, 9, 8, 11]]])
print(array_triple)

print("---------------------------------")

subarray1 = array_triple[0, : , : 2]
print(subarray1)

print("---------------------------------")

subarray2 = array_triple[2, : , : ]
print(subarray2)

[[[14 21  2 20 28]
  [28 15 14 25  6]]

 [[10 25 26 27  8]
  [14  7 22 28  2]]

 [[ 3 10 10 10 13]
  [ 3 19  9  8 11]]]
---------------------------------
[[14 21]
 [28 15]]
---------------------------------
[[ 3 10 10 10 13]
 [ 3 19  9  8 11]]


#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [11]:
#array_cuadruple = np.random.randint(1, 24, (4, 3, 2))
array_cuadruple = np.array([[[10, 17],
                            [ 5, 5],
                            [12, 19]],

                            [[20, 6],
                            [6, 11],
                            [5, 21]],

                            [[21, 12],
                            [16, 18],
                            [20, 19]],

                            [[20,  4],
                            [16, 18],
                            [13, 13]]])

print(array_cuadruple)

print("---------------------------------")

array_cuadruple[1, 1, : ] = 0
print(array_cuadruple)

print("---------------------------------")

array_cuadruple[3, : , : ] = -1
print(array_cuadruple)

[[[10 17]
  [ 5  5]
  [12 19]]

 [[20  6]
  [ 6 11]
  [ 5 21]]

 [[21 12]
  [16 18]
  [20 19]]

 [[20  4]
  [16 18]
  [13 13]]]
---------------------------------
[[[10 17]
  [ 5  5]
  [12 19]]

 [[20  6]
  [ 0  0]
  [ 5 21]]

 [[21 12]
  [16 18]
  [20 19]]

 [[20  4]
  [16 18]
  [13 13]]]
---------------------------------
[[[10 17]
  [ 5  5]
  [12 19]]

 [[20  6]
  [ 0  0]
  [ 5 21]]

 [[21 12]
  [16 18]
  [20 19]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]]



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [12]:
#array_9 = np.random.randint(-10, 14, (2, 4, 3))

array_9 = np.array([[[-8, 10, 3],
                    [10, -9, -1],
                    [12, -8, -10],
                    [9, 5, 2]],

                    [[2, 3, 5],
                    [13, -2, -3],
                    [-8, 2, 3],
                    [3, 1, -3]]])

print(array_9)

print("---------------------------------")

resultado_where = np.where(array_9 > 5)
print(resultado_where)

print("---------------------------------")

array_9[array_9 < 0] = 0
print(array_9)
            

[[[ -8  10   3]
  [ 10  -9  -1]
  [ 12  -8 -10]
  [  9   5   2]]

 [[  2   3   5]
  [ 13  -2  -3]
  [ -8   2   3]
  [  3   1  -3]]]
---------------------------------
(array([0, 0, 0, 0, 1]), array([0, 1, 2, 3, 1]), array([1, 0, 0, 0, 0]))
---------------------------------
[[[ 0 10  3]
  [10  0  0]
  [12  0  0]
  [ 9  5  2]]

 [[ 2  3  5]
  [13  0  0]
  [ 0  2  3]
  [ 3  1  0]]]


#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [18]:
#array_10 = np.random.randint(1, 27, (3, 3, 3))
array_10 = np.array([[[17, 24, 1],
                    [13, 14, 20],
                    [7, 16, 25]],

                    [[14, 9, 23],
                    [14, 6, 25],
                    [5, 4, 25]],

                    [[4, 13, 13],
                    [3, 8, 25],
                    [11, 2, 8]]])

print(array_10)

print("---------------------------------")

subarray3 = array_10[1,:,:2]
print(subarray3)

print("---------------------------------")

subarray4 = array_10[2,:,:]
#print(subarray4)
resultado_20 = np.where(subarray4 < 20)
print(resultado_20)


[[[17 24  1]
  [13 14 20]
  [ 7 16 25]]

 [[14  9 23]
  [14  6 25]
  [ 5  4 25]]

 [[ 4 13 13]
  [ 3  8 25]
  [11  2  8]]]
---------------------------------
[[14  9]
 [14  6]
 [ 5  4]]
---------------------------------
(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 0, 1, 2]))


#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [ ]:
#array_11 = np.random.randint(-10, 11, 10)
array_11 = np.array([7, 4, 9, -4, 5, 3, 2, 2, -1, 7])
print(array_11)

array_11[array_11 == array_11.max()] = 0
array_11[array_11 == array_11.min()] = 0
print(array_11)

[ 7  4  9 -4  5  3  2  2 -1  7]
[ 7  4  0  0  5  3  2  2 -1  7]


#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [19]:
#array_12 = np.random.randint(1, 100, 15)
array_12 = np.array([22, 2, 99, 1, 21, 76, 67, 18, 43, 40, 25, 71, 17, 18, 31])
print(array_12)

ordenado = np.sort(array_12)
print(ordenado)


[22  2 99  1 21 76 67 18 43 40 25 71 17 18 31]
[ 1  2 17 18 18 21 22 25 31 40 43 67 71 76 99]


#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [35]:
#array_13 = np.random.randint(1, 20,(4, 4))
array_13 = np.array([[7, 4, 16, 15],
                    [15, 14, 1, 17],
                    [16, 10, 17, 17],
                    [17, 6, 16, 16]])
print(array_13)

print("---------------------------------")

filas = np.sum(array_13, axis=1)
print(filas)

columnas = np.sum(array_13, axis=0)
print(columnas)


[[ 7  4 16 15]
 [15 14  1 17]
 [16 10 17 17]
 [17  6 16 16]]
---------------------------------
[42 47 60 55]
[55 34 50 65]


#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.